# Site settings
course_name: Mobile Computing
course_description: "This course provides an overview on mobile computing."
course_semester: "Spring 2021"

baseurl: "tanta_mobile_computing.github.io/" # the subpath of your site, e.g. /blog/
url: "https://tantacs.github.io/" # the base hostname & protocol for your site

schoolname: "Tanta University"
schoolurl: "https://eng.tanta.edu.eg/en/"
twitter_username: username 

address: |
    Department of Computer Engineering and Automatic Control
    Faculty of Engineering
    Tanta University

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
